import { Video } from './types';

export const YOUTUBE_CHANNEL_URL = 'https://www.youtube.com/@Dr.SheryarsClassroom';

const LOGO_THUMBNAIL_URL = 'https://storage.googleapis.com/garden-prod/_matt_aic_user_images/40f69542-a1b7-44a7-85b4-22b069d35cb6.png';

export const FEATURED_VIDEOS: Video[] = [
  {
    id: 1,
    title: 'PARTICLE PHYSICS 1',
    subtitle: 'A-LEVEL PHYSICS',
    description: 'Explore the fundamental building blocks of the universe. This lecture covers quarks, leptons, and the forces that govern their interactions as described by the Standard Model.',
    views: '447 views',
    streamed: '5 months ago',
    duration: '2:12:50',
    thumbnailUrl: "https://i.ytimg.com/an_webp/UqyNkzBqux0/mqdefault_6s.webp?du=3000&sqp=COzmscgG&rs=AOn4CLAmREJSZg-0FLRdr1OJJY4j_PVjsQ",
    videoUrl: 'https://youtu.be/UqyNkzBqux0?si=GgnXyIN-wEBi5qez',
    isLive: true,
  },
  {
    id: 2,
    title: 's-Block Elements 01',
    subtitle: 'Basic Properties of s-Block',
    description: 'An introduction to the s-Block elements. Learn about the unique properties of alkali and alkaline earth metals, their electron configurations, and periodic trends.',
    views: '195 views',
    streamed: '5 months ago',
    duration: '2:08:10',
    thumbnailUrl: "https://i.ytimg.com/vi/TJPUax8dlt0/hqdefault.jpg?sqp=-oaymwFBCNACELwBSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYACqgWKAgwIABABGHIgNShtMA8=&rs=AOn4CLC1aollNJjyybUYiHjcnJ3BCAvVZA",
    videoUrl: 'https://youtu.be/TJPUax8dlt0?si=2J2dU78F5z8d2UpN',
    isLive: true,
  },
  {
    id: 3,
    title: 'derivatives 01',
    subtitle: 'differentiation',
    description: 'Grasp the fundamentals of calculus with our introductory lecture on derivatives. We\'ll cover limits, the definition of a derivative, and basic differentiation rules.',
    views: '256 views',
    streamed: '5 months ago',
    duration: '2:12:25',
    thumbnailUrl: "https://i.ytimg.com/vi/ez6xIgM4SX0/hqdefault.jpg?sqp=-oaymwFBCNACELwBSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYACqgWKAgwIABABGHIgNShsMA8=&rs=AOn4CLDWMtvdrtfQPLVV5lcFyvixGGxnWA",
    videoUrl: 'https://youtu.be/ez6xIgM4SX0?si=NGSohxMyH8W4Tnk5',
    isLive: true,
  },
  {
    id: 4,
    title: 'PARTICLE PHYSICS 2',
    subtitle: 'A-LEVEL PHYSICS',
    description: 'Delve deeper into the world of subatomic particles. This session focuses on hadrons, baryons, and mesons, along with the crucial conservation laws in particle physics.',
    views: '447K views',
    streamed: '5 months ago',
    duration: '1:30:15',
    thumbnailUrl: "https://i.ytimg.com/an_webp/Cr-_-BnHM9g/mqdefault_6s.webp?du=3000&sqp=CJCEssgG&rs=AOn4CLCKX5HNYHV9UJGPThq_klnI6dghKQ",
    videoUrl: 'https://youtu.be/Cr-_-BnHM9g?si=QPmgBdGTqal0KvIK',
    isLive: false,
  },
  {
    id: 5,
    title: 'S-Block Elements 02',
    subtitle: 'Basic Properties of s-Block',
    description: 'Continue your study of s-Block elements by examining their important compounds, such as oxides, hydroxides, and carbonates, and their role in industrial applications.',
    views: '200K views',
    streamed: '2 months ago',
    duration: '1:55:42',
    thumbnailUrl: "https://i.ytimg.com/vi/QbJDWb6TNMo/hqdefault.jpg?sqp=-oaymwFBCNACELwBSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYACqgWKAgwIABABGHIgNShtMA8=&rs=AOn4CLDH88K1YlY141T9YdLxBtmk2ppd2A",
    videoUrl: 'https://youtu.be/QbJDWb6TNMo?si=DNCHKONoSBKGTnVc',
    isLive: false,
  },
  {
    id: 6,
    title: 'Derivatives 02',
    subtitle: 'differentiation',
    description: 'Advance your calculus skills by mastering key differentiation techniques, including the product rule, quotient rule, and the powerful chain rule, with practical examples.',
    views: '212K views',
    streamed: '9 months ago',
    duration: '2:05:18',
    thumbnailUrl: "https://i.ytimg.com/vi/LOFtF1UUjGs/hqdefault.jpg?sqp=-oaymwFBCNACELwBSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYACqgWKAgwIABABGHIgNihsMA8=&rs=AOn4CLBq37tu2920jS-eyPaQQEOmOVIt6g",
    videoUrl: 'https://youtu.be/LOFtF1UUjGs?si=lbFjV5jH5jpZG7eK',
    isLive: false,
  },
];
